// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcyiZeykde0oBOTYfIsATkEcqpXEKMpck',
    appId: '1:177321714240:web:b6d86693b5be3324d235a5',
    messagingSenderId: '177321714240',
    projectId: 'crudgetx-95eb8',
    authDomain: 'crudgetx-95eb8.firebaseapp.com',
    storageBucket: 'crudgetx-95eb8.appspot.com',
    measurementId: 'G-NCBCLV5NQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3402O9dBSDcKaDJEdt1fXSDSHfF4K6c',
    appId: '1:177321714240:android:e1c28007dbfd05c7d235a5',
    messagingSenderId: '177321714240',
    projectId: 'crudgetx-95eb8',
    storageBucket: 'crudgetx-95eb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA1lUaU2cheyxRKwvxtW5x4e9DWAlXUtg',
    appId: '1:177321714240:ios:c0f55f8ca0057c5ad235a5',
    messagingSenderId: '177321714240',
    projectId: 'crudgetx-95eb8',
    storageBucket: 'crudgetx-95eb8.appspot.com',
    iosBundleId: 'com.example.crudGetx',
  );
}
